site_name: Luu The Vinh Docs
site_url: https://thevinhluu.github.io/mkdocs
site_description: Dự án học tập cá nhân
site_author: Lưu Thế Vinh

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Trang Chủ: index.md
  - API and Web Development:
      - Giới thiệu: api_and_web/index.md
      - HTTP: api_and_web/http.md
      - REST API: api_and_web/rest_api_cheatsheet.md
      - gRPC: api_and_web/grpc.md
      - WebSockets: api_and_web/websockets.md
  - Database and Storage: database_and_storage.md
  - Caching & Performance: caching_and_performance.md
  - Software Architecture: software_architecture.md
  - Software Development: software_development.md
  - DevTools & Productivity: devtools_productivity.md
  - Cloud & Distributed Systems: cloud_distributed.md
  - DevOps and CI/CD: devops_cicd.md
  - Security: security.md
  - Computer Fundamentals: computer_fundamentals.md
  - Real World Case Studies: real_world_case_studies.md
  - AI và Machine Learning: ai_machine_learning.md
  - Technical Interviews: technical_interviews.md
  - Payment và Fintech: payment_fintech.md
  - How it Works?: how_it_works.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thevinhluu/mkdocs
    - icon: fontawesome/brands/facebook
      link: "https://www.facebook.com/luuthevinh105/"

plugins:
  - search
